version: 0.0
os: linux

files:
  - source: ./
    destination: /spring-boot-helloworld/release

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/BeforInstall.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 60
      runas: ec2-user
