version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
       - echo "Pre build stage"
       - yum install -y curl
       - java -version
       - ls -al 
  build:
    commands:
       - echo "Build stage"
       - ./gradlew build --debug
  post_build:
    commands:
       - echo "Post build stage"
       - nohup java -jar -Dserver.port=$PORT ./build/libs/spring-boot-helloworld-0.0.1-SNAPSHOT.jar >/dev/null 2>&1 &
       - sleep 60
       - curl localhost:8080
       - sh spring-boot-helloworld/script/service_validate.sh
       - sudo killall java
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
